name: "Release Docs Check"
on: 
  release:
    types: [published]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: uibcdf/action-sphinx-docs-to-gh-pages@v2.1.0
        with:
          branch: main
          dir_docs: docs
          sphinx-apidoc-opts: "--separate -o . ../"
          sphinx-apidoc-exclude: "../*setup* ../*.ipynb"
          sphinx-opts: ""
