name: Test
on: [release, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
        
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install .
          
      - name: Test and Coverage
        run: python -m pytest --cov --cov-report json

      - name: Update Coverage Badge
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: we-cli/coverage-badge-action@main
